In [1]:
import pandas as pd

In [3]:
import os

print(os.getcwd())

c:\Users\M.SATHVIKA\OneDrive\BLUESTOCK INTERNSHIP\mutual_fund_analysis

In [4]:
import os

print(os.listdir())

['.git', 'amfi_validation.py', 'dashboard', 'data', 'data_ingestion.py', 'day2_cleaning.ipynb', 'fund_master_exploration.py', 'live_nav_fetch.py', 'notebooks', 'README.md', 'reports', 'requirements.txt', 'sql']

In [5]:
import os

print(os.listdir("data"))

['processed', 'raw']

In [6]:
import os

print(os.listdir("data/raw"))

['01_fund_master.csv', '02_nav_history.csv', '03_aum_by_fund_house.csv', '04_monthly_sip_inflows.csv', '05_category_inflows.csv', '06_industry_folio_count.csv', '07_scheme_performance.csv', '08_investor_transactions.csv', '09_portfolio_holdings.csv', '10_benchmark_indices.csv', 'live_nav']

In [7]:
import pandas as pd

nav = pd.read_csv("data/raw/02_nav_history.csv")

nav.head()

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [8]:
nav.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  object
 2   nav        46000 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.1+ MB

In [9]:
nav['date'] = pd.to_datetime(nav['date'])

nav.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  datetime64[ns]
 2   nav        46000 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(1)
memory usage: 1.1 MB

In [10]:
nav = nav.sort_values(
    ['amfi_code', 'date']
)

nav.head()

      amfi_code       date       nav
5750     100016 2022-01-03  520.4608
5751     100016 2022-01-04  515.0971
5752     100016 2022-01-05  521.7239
5753     100016 2022-01-06  515.7880
5754     100016 2022-01-07  515.1639

In [11]:
nav.isnull().sum()

amfi_code    0
date         0
nav          0
dtype: int64

In [12]:
nav.duplicated().sum()

np.int64(0)

In [13]:
(nav['nav'] <= 0).sum()

np.int64(0)

In [14]:
nav = nav.sort_values(['amfi_code', 'date'])

nav.to_csv(
    "data/processed/02_nav_history_clean.csv",
    index=False
)

print("NAV file cleaned and saved!")

NAV file cleaned and saved!

In [15]:
import os

print(os.listdir("data/processed"))

['02_nav_history_clean.csv']

In [16]:
txn = pd.read_csv("data/raw/08_investor_transactions.csv")
txn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32778 entries, 0 to 32777
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   investor_id         32778 non-null  object
 1   transaction_date    32778 non-null  object
 2   amfi_code           32778 non-null  int64
 3   transaction_type    32778 non-null  object
 4   amount_inr          32778 non-null  int64
 5   state               32778 non-null  object
 6   city                32778 non-null  object
 7   city_tier           32778 non-null  object
 8   age_group           32778 non-null  object
 9   gender              32778 non-null  object
 10  annual_income_lakh  32778 non-null  float64
 11  payment_mode        32778 non-null  object
 12  kyc_status          32778 non-null  object
dtypes: float64(1), int64(2), object(10)
memory usage: 3.3+ MB

In [17]:
txn['transaction_date'] = pd.to_datetime(
    txn['transaction_date']
)

txn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32778 entries, 0 to 32777
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   investor_id         32778 non-null  object
 1   transaction_date    32778 non-null  datetime64[ns]
 2   amfi_code           32778 non-null  int64
 3   transaction_type    32778 non-null  object
 4   amount_inr          32778 non-null  int64
 5   state               32778 non-null  object
 6   city                32778 non-null  object
 7   city_tier           32778 non-null  object
 8   age_group           32778 non-null  object
 9   gender              32778 non-null  object
 10  annual_income_lakh  32778 non-null  float64
 11  payment_mode        32778 non-null  object
 12  kyc_status          32778 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(2), object(9)
memory usage: 3.3+ MB

In [18]:
txn['transaction_type'].unique()

array(['SIP', 'Redemption', 'Lumpsum'], dtype=object)

In [19]:
txn['kyc_status'].unique()

array(['Verified', 'Pending'], dtype=object)

In [20]:
(txn['amount_inr'] <= 0).sum()

np.int64(0)

In [21]:
txn.to_csv(
    "data/processed/08_investor_transactions_clean.csv",
    index=False
)

print("Transactions file cleaned and saved!")

Transactions file cleaned and saved!

In [22]:
perf = pd.read_csv(
    "data/raw/07_scheme_performance.csv"
)

perf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   scheme_name         40 non-null     object
 2   fund_house          40 non-null     object
 3   category            40 non-null     object
 4   plan                40 non-null     object
 5   return_1yr_pct      40 non-null     float64
 6   return_3yr_pct      40 non-null     float64
 7   return_5yr_pct      40 non-null     float64
 8   benchmark_3yr_pct   40 non-null     float64
 9   alpha               40 non-null     float64
 10  beta                40 non-null     float64
 11  sharpe_ratio        40 non-null     float64
 12  sortino_ratio       40 non-null     float64
 13  std_dev_ann_pct     40 non-null     float64
 14  max_drawdown_pct    40 non-null     float64
 15  aum_crore           40 non-null     int64
 16  expense_ratio_pct   40 non-null     float64
 17  morningstar_rating  40 non-null     int64
 18  risk_grade          40 non-null     object
dtypes: float64(11), int64(3), object(5)
memory usage: 6.1+ KB

In [23]:
perf[
    (perf['expense_ratio_pct'] < 0.1) |
    (perf['expense_ratio_pct'] > 2.5)
]

Empty DataFrame
Columns: [amfi_code, scheme_name, fund_house, category, plan, return_1yr_pct, return_3yr_pct, return_5yr_pct, benchmark_3yr_pct, alpha, beta, sharpe_ratio, sortino_ratio, std_dev_ann_pct, max_drawdown_pct, aum_crore, expense_ratio_pct, morningstar_rating, risk_grade]
Index: []

In [24]:
perf.isnull().sum()

amfi_code             0
scheme_name           0
fund_house            0
category              0
plan                  0
return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
risk_grade            0
dtype: int64

In [25]:
perf[
    (perf['return_1yr_pct'] > 100) |
    (perf['return_1yr_pct'] < -100)
]

Empty DataFrame
Columns: [amfi_code, scheme_name, fund_house, category, plan, return_1yr_pct, return_3yr_pct, return_5yr_pct, benchmark_3yr_pct, alpha, beta, sharpe_ratio, sortino_ratio, std_dev_ann_pct, max_drawdown_pct, aum_crore, expense_ratio_pct, morningstar_rating, risk_grade]
Index: []

In [26]:
perf.to_csv(
    "data/processed/07_scheme_performance_clean.csv",
    index=False
)

print("Scheme performance file cleaned and saved!")

Scheme performance file cleaned and saved!

In [28]:
from sqlalchemy import create_engine

In [29]:
from sqlalchemy import create_engine

engine = create_engine(
    "sqlite:///bluestock_mf.db"
)

print("Database created successfully!")

Database created successfully!

In [30]:
import pandas as pd

nav = pd.read_csv("data/processed/02_nav_history_clean.csv")
txn = pd.read_csv("data/processed/08_investor_transactions_clean.csv")
perf = pd.read_csv("data/processed/07_scheme_performance_clean.csv")

print(nav.shape)
print(txn.shape)
print(perf.shape)

(46000, 3)
(32778, 13)
(40, 19)

In [31]:
nav.to_sql(
    "fact_nav",
    engine,
    if_exists="replace",
    index=False
)

txn.to_sql(
    "fact_transactions",
    engine,
    if_exists="replace",
    index=False
)

perf.to_sql(
    "fact_performance",
    engine,
    if_exists="replace",
    index=False
)

print("Tables loaded successfully!")

Tables loaded successfully!

In [32]:
import sqlite3

conn = sqlite3.connect("bluestock_mf.db")

print(pd.read_sql(
    "SELECT COUNT(*) AS rows FROM fact_nav",
    conn
))

print(pd.read_sql(
    "SELECT COUNT(*) AS rows FROM fact_transactions",
    conn
))

print(pd.read_sql(
    "SELECT COUNT(*) AS rows FROM fact_performance",
    conn
))

    rows
0  46000
    rows
0  32778
   rows
0    40

In [ ]:
aum = pd.read_csv(
    "data/raw/03_aum_by_fund_house.csv"
)

aum.info()